version: '2'

services:
  mysql:
    image: docker.io/bitnami/mariadb:11.2.2
    environment:
    - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
    - MARIADB_USER=${MARIADB_USER}
    - MARIADB_PASSWORD=${MARIADB_PASSWORD}
    - MARIADB_DATABASE=db
    volumes:
    - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
    - ./mariadb/conf.d/my_custom.cnf:/opt/bitnami/mariadb/conf/my_custom.cnf:ro
    - mysql-log:/var/log/mysql
  web:
    build: 
      context: php
    volumes:
    - ./src:/var/www/html:ro
    ports:
    - "127.0.0.1:8181:80"

volumes:
  mysql-log:
    driver: local
