version: '2'

services:
  mysql:
    image: docker.io/bitnami/mariadb:11.2.2
    environment:
    - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
    - MARIADB_USER=${MARIADB_USER}
    - MARIADB_PASSWORD=${MARIADB_PASSWORD}
    - MARIADB_DATABASE=db
    volumes:
    - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
    - ./mysql/conf.d:/etc/mysql/conf.d:ro
    - mysql-log:/var/log/mysql
  # https://docs.bitnami.com/tutorials/develop-http-api-php-containers/
  php:
    build:
      context: php
    environment:
      - MARIADB_HOST=mysql
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
      - MARIADB_DATABASE=db
    volumes:
      - ./php/src:/app:rw
  apache:
    image: docker.io/bitnami/apache:2.4.58
    ports:
      - "127.0.0.1:8181:8080"
    volumes:
      - ./apache-vhost/myapp.conf:/vhosts/myapp.conf:ro
      - ./php/src:/app:ro
    depends_on:
      - php

volumes:
  mysql-log:
    driver: local
