version: '2'

services:
  mysql:
    image: pyriand3r/i386-mysql:5.7
    environment:
    - MYSQL_RANDOM_ROOT_PASSWORD=yes
    - MYSQL_USER=mysql
    - MYSQL_PASSWORD=mysql
    - MYSQL_DATABASE=db
    volumes:
    - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    - ./mysql/conf.d:/etc/mysql/conf.d
    - mysql-log:/var/log/mysql
    - ./src:/var/www/html
  web:
    build: 
      context: php
    volumes:
    - ./src:/var/www/html
    ports:
    - 127.0.0.1:8181:80

volumes:
  mysql-log:
    driver: local
